### ISSUE TITLE
Not able to start GPU training for multiway modeling

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#405]
Hi,

I have updated to `version 1.22.0` and Transformer model fails with GPU OOM error. Kinda know its a well known error and I have solved it in the past, but past method doesn't seem to work now I have tried the following : 
- tried with Autotuner for batch size by setting train `batch_size` and `effective_batch_size` to `null`. I see that autotuner doesn't go below 1024 and tries and fails to start training at 1024.
- I change `batch_size` to 16 and `max_features_length` & `maximum_labels_length` to 50 and still fails. 

Attached is the log file for passed configurations and error details:
[multi_rnn_testrun4.log](https://github.com/OpenNMT/OpenNMT-tf/files/3076744/multi_rnn_testrun4.log)

Also, my run command looks like below:
`onmt-main train_and_eval --model_type Transformer --config /home/ubuntu/multilingual_data_ayub/config_run_da_nfpa.yml --auto_config --num_gpus 1 2>&1 | tee /home/ubuntu/multilingual_data_ayub/multi_rnn_testrun4.log`

I had run similar experiment on version 1.15.0 and it seems to run just fine. The only thing changed in this experiment is I added more sentences in source file (about 1 Million more). Not sure where I'm going wrong here.

Thanks !

**Comment by mohammedayub44** [comment]
I got it to work. My bad,  I was running this as background process, my GPU was being occupied by my previous runs and had not been killed.
