### ISSUE TITLE
low GPU usage

### ISSUE THREAD

**Issue by eveliao** [OpenNMT/OpenNMT-tf#638]
I installed the latest version `2.8.1` . tf version is `2.1.0` and cuda version is `10.2`.
I simply copied the code from `examples/library/custom_transformer_training.py` and set `batch_size=512`.
However, the running process only occupies about 153MB GPU no matter the batch_size.

This is the message when 'import opennmt':
```
>>> import opennmt
2020-03-27 12:29:53.941589: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64
2020-03-27 12:29:53.941708: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64
2020-03-27 12:29:53.941726: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```
How can I fix this?

**Comment by guillaumekln** [comment]
TensorFlow 2.1 requires CUDA 10.1, not 10.2.

See the related TensorFlow documentation: https://www.tensorflow.org/install/gpu

**Comment by eveliao** [comment]
Thanks!
Problem solved after installing CUDA 10.1 and add one line to code:
`os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'`
