### ISSUE TITLE
GPU OOM issue

### ISSUE THREAD

**Issue by xustev75** [OpenNMT/OpenNMT-tf#741]
# my setup:
OS: Linux version 5.4.0-48-generic (buildd@lcy01-amd64-010) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))
GPU: GeForce GTX 1080 Ti 
GPU Memory: 11177MiB
openNMT-tf version: 2.12.1

# my training: 
onmt-main --gpu_allow_growth --model_type Transformer --config config/toy_zhen.yaml --auto_config train --with_eval

# the problem
getting out of memory error
It looks like:
1. tensorflow allocate most of GPU memory when starting up (with --gpu_allow_growth option, it started a lower allocation but soon to almost full memory
2. saved first checkpoint
3. when creating summary at 100, it tries to allocate more memory and fail

# my config 
```yaml
data:
  eval_features_file: eval/en2cn-2k.zh.tok
  eval_labels_file: eval/en2cn-2k.en.txt
  source_tokenization: config/conservative.yml
  source_vocabulary: train/news-commentary-v15.zh.vocab
  target_tokenization: config/conservative.yml
  target_vocabulary: train/news-commentary-v15.en.vocab
  train_features_file: train/news-commentary-v15.zh.tok
  train_labels_file: train/news-commentary-v15.en.tok
eval:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
infer:
  batch_size: 32
  batch_type: examples
  length_bucket_width: 5
model_dir: run/
params:
  average_loss_in_time: true
  beam_width: 4
  decay_params:
    model_dim: 512
    warmup_steps: 8000
  decay_type: NoamDecay
  label_smoothing: 0.1
  learning_rate: 2.0
  num_hypotheses: 1
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
score:
  batch_size: 64
train:
  average_last_checkpoints: 8
  batch_size: 64
  batch_type: examples
  effective_batch_size: 10000
  keep_checkpoint_max: 8
  length_bucket_width: 1
  max_step: 20000
  maximum_features_length: 100
  maximum_labels_length: 100
  sample_buffer_size: 5000
  save_checkpoints_step: 100
  save_summary_steps: 100
```

**Comment by xustev75** [comment]
# stack trace
2020-11-12 16:31:36.783075: W tensorflow/core/common_runtime/bfc_allocator.cc:439] ******************************************************************************************__________
Traceback (most recent call last):
  File "/home/tingdong/.local/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/bin/main.py", line 227, in main
    runner.train(
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/runner.py", line 228, in train
    trainer(
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/training.py", line 93, in __call__
    for loss in self._steps(dataset, accum_steps=accum_steps, report_steps=report_steps):
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/training.py", line 219, in _steps
    loss = _forward()
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/tingdong/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  Ran out of GPU memory when allocating 1139222784 bytes for
         [[node softmax_cross_entropy_with_logits (defined at /lib/python3.8/site-packages/opennmt/utils/losses.py:22) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
RunOptions for current allocation info.
 [Op:__inference__forward_33047]

**Comment by xustev75** [comment]
# GPU status at time of failure
Thu Nov 12 16:31:26 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:03:00.0 Off |                  N/A |
| 47%   80C    P2   250W / 250W |  10719MiB / 11177MiB |     98%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       991      G   /usr/lib/xorg/Xorg                 90MiB |
|    0   N/A  N/A      1213      G   /usr/bin/gnome-shell                8MiB |
|    0   N/A  N/A   2471844      C   /usr/bin/python3                10615MiB |
+-----------------------------------------------------------------------------+

**Comment by xustev75** [comment]
Change batch_type from examples to tokens and the problem went away. 
Why is that though?

**Comment by guillaumekln** [comment]
What is the size of your vocabulary?

**Comment by xustev75** [comment]
my vocab size was 50000

**Comment by guillaumekln** [comment]
Looks like there is no bug. You should adapt the batch size depending on your model size.
